spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: aswadh12345
  jpa:
    hibernate .ddl-auto: update
    generate -ddl: true
    show-sql: true
